<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260610201212 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE sector (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4BA3D9E8727ACA70 ON sector (parent_id)');
        $this->addSql('CREATE TABLE submission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, agree_to_terms BOOLEAN NOT NULL, session_id VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE submission_sector (submission_id INT NOT NULL, sector_id INT NOT NULL, PRIMARY KEY (submission_id, sector_id))');
        $this->addSql('CREATE INDEX IDX_73A68456E1FD4933 ON submission_sector (submission_id)');
        $this->addSql('CREATE INDEX IDX_73A68456DE95C867 ON submission_sector (sector_id)');
        $this->addSql('ALTER TABLE sector ADD CONSTRAINT FK_4BA3D9E8727ACA70 FOREIGN KEY (parent_id) REFERENCES sector (id)');
        $this->addSql('ALTER TABLE submission_sector ADD CONSTRAINT FK_73A68456E1FD4933 FOREIGN KEY (submission_id) REFERENCES submission (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE submission_sector ADD CONSTRAINT FK_73A68456DE95C867 FOREIGN KEY (sector_id) REFERENCES sector (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE sector DROP CONSTRAINT FK_4BA3D9E8727ACA70');
        $this->addSql('ALTER TABLE submission_sector DROP CONSTRAINT FK_73A68456E1FD4933');
        $this->addSql('ALTER TABLE submission_sector DROP CONSTRAINT FK_73A68456DE95C867');
        $this->addSql('DROP TABLE sector');
        $this->addSql('DROP TABLE submission');
        $this->addSql('DROP TABLE submission_sector');
    }
}
