--
-- PostgreSQL database dump
--

\restrict 9N7scGs3YHefePiIgAplLHA6XpAxM4bGmhn3XNMmF5uJt9IXcAizBKn5mViadDh

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: helmes
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO helmes;

--
-- Name: sector; Type: TABLE; Schema: public; Owner: helmes
--

CREATE TABLE public.sector (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    parent_id integer
);


ALTER TABLE public.sector OWNER TO helmes;

--
-- Name: sector_id_seq; Type: SEQUENCE; Schema: public; Owner: helmes
--

ALTER TABLE public.sector ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sector_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: submission; Type: TABLE; Schema: public; Owner: helmes
--

CREATE TABLE public.submission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    agree_to_terms boolean NOT NULL,
    session_id character varying(255) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL
);


ALTER TABLE public.submission OWNER TO helmes;

--
-- Name: submission_id_seq; Type: SEQUENCE; Schema: public; Owner: helmes
--

ALTER TABLE public.submission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.submission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: submission_sector; Type: TABLE; Schema: public; Owner: helmes
--

CREATE TABLE public.submission_sector (
    submission_id integer NOT NULL,
    sector_id integer NOT NULL
);


ALTER TABLE public.submission_sector OWNER TO helmes;

--
-- Data for Name: doctrine_migration_versions; Type: TABLE DATA; Schema: public; Owner: helmes
--

COPY public.doctrine_migration_versions (version, executed_at, execution_time) FROM stdin;
DoctrineMigrations\\Version20260610201212	2026-06-10 20:12:51	31
\.


--
-- Data for Name: sector; Type: TABLE DATA; Schema: public; Owner: helmes
--

COPY public.sector (id, name, parent_id) FROM stdin;
159	Manufacturing	\N
160	Construction materials	159
161	Electronics and Optics	159
162	Food and Beverage	159
163	Bakery & confectionery products	162
164	Beverages	162
165	Fish & fish products	162
166	Meat & meat products	162
167	Milk & dairy products	162
168	Other	162
169	Sweets & snack food	162
170	Furniture	159
171	Bathroom/sauna	170
172	Bedroom	170
173	Children's room	170
174	Kitchen	170
175	Living room	170
176	Office	170
177	Other (Furniture)	170
178	Outdoor	170
179	Project furniture	170
180	Machinery	159
181	Machinery components	180
182	Machinery equipment/tools	180
183	Manufacture of machinery	180
184	Maritime	180
185	Aluminium and steel workboats	184
186	Boat/Yacht building	184
187	Ship repair and conversion	184
188	Metal structures	180
189	Other	180
190	Repair and maintenance service	180
191	Metalworking	159
192	Construction of metal structures	191
193	Houses and buildings	191
194	Metal products	191
195	Metal works	191
196	CNC-machining	195
197	Forgings, Fasteners	195
198	Gas, Plasma, Laser cutting	195
199	MIG, TIG, Aluminum welding	195
200	Plastic and Rubber	159
201	Packaging	200
202	Plastic goods	200
203	Plastic processing technology	200
204	Blowing	203
205	Moulding	203
206	Plastics welding and processing	203
207	Plastic profiles	200
208	Printing	159
209	Advertising	208
210	Book/Periodicals printing	208
211	Labelling and packaging printing	208
212	Textile and Clothing	159
213	Clothing	212
214	Textile	212
215	Wood	159
216	Other (Wood)	215
217	Wooden building materials	215
218	Wooden houses	215
219	Other	\N
220	Creative industries	219
221	Energy technology	219
222	Environment	219
223	Service	\N
224	Business services	223
225	Engineering	223
226	Information Technology and Telecommunications	223
227	Data processing, Web portals, E-marketing	226
228	Programming, Consultancy	226
229	Software, Hardware	226
230	Telecommunications	226
231	Tourism	223
232	Translation services	223
233	Transport and Logistics	223
234	Air	233
235	Rail	233
236	Road	233
237	Water	233
\.


--
-- Data for Name: submission; Type: TABLE DATA; Schema: public; Owner: helmes
--

COPY public.submission (id, name, agree_to_terms, session_id, created_at) FROM stdin;
\.


--
-- Data for Name: submission_sector; Type: TABLE DATA; Schema: public; Owner: helmes
--

COPY public.submission_sector (submission_id, sector_id) FROM stdin;
\.


--
-- Name: sector_id_seq; Type: SEQUENCE SET; Schema: public; Owner: helmes
--

SELECT pg_catalog.setval('public.sector_id_seq', 237, true);


--
-- Name: submission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: helmes
--

SELECT pg_catalog.setval('public.submission_id_seq', 1, false);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: helmes
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- Name: sector sector_pkey; Type: CONSTRAINT; Schema: public; Owner: helmes
--

ALTER TABLE ONLY public.sector
    ADD CONSTRAINT sector_pkey PRIMARY KEY (id);


--
-- Name: submission submission_pkey; Type: CONSTRAINT; Schema: public; Owner: helmes
--

ALTER TABLE ONLY public.submission
    ADD CONSTRAINT submission_pkey PRIMARY KEY (id);


--
-- Name: submission_sector submission_sector_pkey; Type: CONSTRAINT; Schema: public; Owner: helmes
--

ALTER TABLE ONLY public.submission_sector
    ADD CONSTRAINT submission_sector_pkey PRIMARY KEY (submission_id, sector_id);


--
-- Name: idx_4ba3d9e8727aca70; Type: INDEX; Schema: public; Owner: helmes
--

CREATE INDEX idx_4ba3d9e8727aca70 ON public.sector USING btree (parent_id);


--
-- Name: idx_73a68456de95c867; Type: INDEX; Schema: public; Owner: helmes
--

CREATE INDEX idx_73a68456de95c867 ON public.submission_sector USING btree (sector_id);


--
-- Name: idx_73a68456e1fd4933; Type: INDEX; Schema: public; Owner: helmes
--

CREATE INDEX idx_73a68456e1fd4933 ON public.submission_sector USING btree (submission_id);


--
-- Name: sector fk_4ba3d9e8727aca70; Type: FK CONSTRAINT; Schema: public; Owner: helmes
--

ALTER TABLE ONLY public.sector
    ADD CONSTRAINT fk_4ba3d9e8727aca70 FOREIGN KEY (parent_id) REFERENCES public.sector(id);


--
-- Name: submission_sector fk_73a68456de95c867; Type: FK CONSTRAINT; Schema: public; Owner: helmes
--

ALTER TABLE ONLY public.submission_sector
    ADD CONSTRAINT fk_73a68456de95c867 FOREIGN KEY (sector_id) REFERENCES public.sector(id) ON DELETE CASCADE;


--
-- Name: submission_sector fk_73a68456e1fd4933; Type: FK CONSTRAINT; Schema: public; Owner: helmes
--

ALTER TABLE ONLY public.submission_sector
    ADD CONSTRAINT fk_73a68456e1fd4933 FOREIGN KEY (submission_id) REFERENCES public.submission(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict 9N7scGs3YHefePiIgAplLHA6XpAxM4bGmhn3XNMmF5uJt9IXcAizBKn5mViadDh

