--
-- PostgreSQL database dump
--

\restrict kXCuo3AMm0IOokfgJijD9uoLHrcNevvSJYyuHDIDccIeMUoHqXympndyYKzsuVD

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: helmes
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO helmes;

--
-- Name: sector; Type: TABLE; Schema: public; Owner: helmes
--

CREATE TABLE public.sector (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    parent_id integer
);


ALTER TABLE public.sector OWNER TO helmes;

--
-- Name: sector_id_seq; Type: SEQUENCE; Schema: public; Owner: helmes
--

ALTER TABLE public.sector ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sector_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: submission; Type: TABLE; Schema: public; Owner: helmes
--

CREATE TABLE public.submission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    agree_to_terms boolean NOT NULL,
    session_id character varying(255) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL
);


ALTER TABLE public.submission OWNER TO helmes;

--
-- Name: submission_id_seq; Type: SEQUENCE; Schema: public; Owner: helmes
--

ALTER TABLE public.submission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.submission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: submission_sector; Type: TABLE; Schema: public; Owner: helmes
--

CREATE TABLE public.submission_sector (
    submission_id integer NOT NULL,
    sector_id integer NOT NULL
);


ALTER TABLE public.submission_sector OWNER TO helmes;

--
-- Data for Name: doctrine_migration_versions; Type: TABLE DATA; Schema: public; Owner: helmes
--

COPY public.doctrine_migration_versions (version, executed_at, execution_time) FROM stdin;
DoctrineMigrations\\Version20260610201212	2026-06-10 20:12:51	31
\.


--
-- Data for Name: sector; Type: TABLE DATA; Schema: public; Owner: helmes
--

COPY public.sector (id, name, parent_id) FROM stdin;
80	Manufacturing	\N
81	Construction materials	80
82	Electronics and Optics	80
83	Food and Beverage	80
84	Bakery & confectionery products	83
85	Beverages	83
86	Fish & fish products	83
87	Meat & meat products	83
88	Milk & dairy products	83
89	Other	83
90	Sweets & snack food	83
91	Furniture	80
92	Bathroom/sauna	91
93	Bedroom	91
94	Children's room	91
95	Kitchen	91
96	Living room	91
97	Office	91
98	Other (Furniture)	91
99	Outdoor	91
100	Project furniture	91
101	Machinery	80
102	Machinery components	101
103	Machinery equipment/tools	101
104	Manufacture of machinery	101
105	Maritime	101
106	Aluminium and steel workboats	105
107	Boat/Yacht building	105
108	Ship repair and conversion	105
109	Metal structures	101
110	Other	101
111	Repair and maintenance service	101
112	Metalworking	80
113	Construction of metal structures	112
114	Houses and buildings	112
115	Metal products	112
116	Metal works	112
117	CNC-machining	116
118	Forgings, Fasteners	116
119	Gas, Plasma, Laser cutting	116
120	MIG, TIG, Aluminum welding	116
121	Plastic and Rubber	80
122	Packaging	121
123	Plastic goods	121
124	Plastic processing technology	121
125	Blowing	124
126	Moulding	124
127	Plastics welding and processing	124
128	Plastic profiles	121
129	Printing	80
130	Advertising	129
131	Book/Periodicals printing	129
132	Labelling and packaging printing	129
133	Textile and Clothing	80
134	Clothing	133
135	Textile	133
136	Wood	80
137	Other (Wood)	136
138	Wooden building materials	136
139	Wooden houses	136
140	Other	\N
141	Creative industries	140
142	Energy technology	140
143	Environment	140
144	Service	\N
145	Business services	144
146	Engineering	144
147	Information Technology and Telecommunications	144
148	Data processing, Web portals, E-marketing	147
149	Programming, Consultancy	147
150	Software, Hardware	147
151	Telecommunications	147
152	Tourism	144
153	Translation services	144
154	Transport and Logistics	144
155	Air	154
156	Rail	154
157	Road	154
158	Water	154
\.


--
-- Data for Name: submission; Type: TABLE DATA; Schema: public; Owner: helmes
--

COPY public.submission (id, name, agree_to_terms, session_id, created_at) FROM stdin;
\.


--
-- Data for Name: submission_sector; Type: TABLE DATA; Schema: public; Owner: helmes
--

COPY public.submission_sector (submission_id, sector_id) FROM stdin;
\.


--
-- Name: sector_id_seq; Type: SEQUENCE SET; Schema: public; Owner: helmes
--

SELECT pg_catalog.setval('public.sector_id_seq', 158, true);


--
-- Name: submission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: helmes
--

SELECT pg_catalog.setval('public.submission_id_seq', 1, false);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: helmes
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- Name: sector sector_pkey; Type: CONSTRAINT; Schema: public; Owner: helmes
--

ALTER TABLE ONLY public.sector
    ADD CONSTRAINT sector_pkey PRIMARY KEY (id);


--
-- Name: submission submission_pkey; Type: CONSTRAINT; Schema: public; Owner: helmes
--

ALTER TABLE ONLY public.submission
    ADD CONSTRAINT submission_pkey PRIMARY KEY (id);


--
-- Name: submission_sector submission_sector_pkey; Type: CONSTRAINT; Schema: public; Owner: helmes
--

ALTER TABLE ONLY public.submission_sector
    ADD CONSTRAINT submission_sector_pkey PRIMARY KEY (submission_id, sector_id);


--
-- Name: idx_4ba3d9e8727aca70; Type: INDEX; Schema: public; Owner: helmes
--

CREATE INDEX idx_4ba3d9e8727aca70 ON public.sector USING btree (parent_id);


--
-- Name: idx_73a68456de95c867; Type: INDEX; Schema: public; Owner: helmes
--

CREATE INDEX idx_73a68456de95c867 ON public.submission_sector USING btree (sector_id);


--
-- Name: idx_73a68456e1fd4933; Type: INDEX; Schema: public; Owner: helmes
--

CREATE INDEX idx_73a68456e1fd4933 ON public.submission_sector USING btree (submission_id);


--
-- Name: sector fk_4ba3d9e8727aca70; Type: FK CONSTRAINT; Schema: public; Owner: helmes
--

ALTER TABLE ONLY public.sector
    ADD CONSTRAINT fk_4ba3d9e8727aca70 FOREIGN KEY (parent_id) REFERENCES public.sector(id);


--
-- Name: submission_sector fk_73a68456de95c867; Type: FK CONSTRAINT; Schema: public; Owner: helmes
--

ALTER TABLE ONLY public.submission_sector
    ADD CONSTRAINT fk_73a68456de95c867 FOREIGN KEY (sector_id) REFERENCES public.sector(id) ON DELETE CASCADE;


--
-- Name: submission_sector fk_73a68456e1fd4933; Type: FK CONSTRAINT; Schema: public; Owner: helmes
--

ALTER TABLE ONLY public.submission_sector
    ADD CONSTRAINT fk_73a68456e1fd4933 FOREIGN KEY (submission_id) REFERENCES public.submission(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict kXCuo3AMm0IOokfgJijD9uoLHrcNevvSJYyuHDIDccIeMUoHqXympndyYKzsuVD

